version: '3'
services:
    db:
      image: postgres:11.2
      container_name: db
      ports:
        - 5432:5432
      volumes:
        - ./docker/db/initdb:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      hostname: postgres
      restart: always
      user: postgres

    pgadmin4:
      image: dpage/pgadmin4:4.2
      container_name: pgadmin4
      ports:
        - 8080:80
      volumes:
        - ./pgadmin:/var/lib/pgadmin/storage
      environment:
        PGADMIN_DEFAULT_EMAIL: root
        PGADMIN_DEFAULT_PASSWORD: root
      hostname: pgadmin4
      depends_on:
          - db
      restart: always
